# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
       AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        in_memory:
            memory: ~
        our_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login
                check_path: login
                use_referer: true
            provider: our_provider

            logout:
                path:   /logout
                target: /login
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/atividade/extra, roles: ROLE_USER }
            - { path: ^/cronograma/saveExtra, roles: ROLE_USER }
            - { path: ^/atividade/meuHorario/[0-9]+, roles: ROLE_USER }
            - { path: ^/colaborador/edita/[0-9]+, roles: ROLE_USER }
            - { path: ^/colaborador/save/[0-9]+, roles: ROLE_USER }
            - { path: ^/atividade, roles: ROLE_ADMIN }
            - { path: ^/cronograma, roles: ROLE_ADMIN }
            - { path: ^/colaborador, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER }
            - { path: ^/, roles: ROLE_ADMIN }
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
