AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Entity\UserRepository
    table: app_users
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        username:
            type: string
            lenght: 25
        password:
            type: string
            lenght: 64
        email:
            type: string
            length: 60
        nome:
            type: string
            lenght: 100
        quarto:
            type: string
            lenght: 25
            nullable: true
        is_active:
            type: boolean
            nullable: true
            options:
                default: 1
        role:
            type: string
            length: 25
    oneToMany:
        horarios:
            targetEntity: Horario
            mappedBy: user
