<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * CronogramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronogramaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findIdByUser($idHorario)
	{
		$horario = $this->getEntityManager('AppBundle:Horario')->createQuery(
			"SELECT h FROM AppBundle:Horario h WHERE h.id = {$idHorario}"			
		)->getResult();

		foreach($horario as $k => $v){
			$result[$k]['user_id'] = $v->getUser()->getNome();
		}

		return json_encode($result);
	}

	public function findHorarioByLocal($idLocal)
	{
		$atividade = $this->getEntityManager('AppBundle:Atividade')->createQuery(
			"SELECT a FROM AppBundle:Atividade a WHERE a.id = {$idLocal}"			
		)->getResult();

		foreach($atividade as $k => $v){
			$result[$k]['horario'] = $v->getHorarioDe()." - ".$v->getHorarioAte();
		}

		return json_encode($result);
	}

	public function findCronogramaByUser($id)
	{

		return $cronograma = $this->getEntityManager()->createQuery(
			"SELECT c FROM AppBundle:Cronograma as c
			INNER JOIN AppBundle:Horario as h
			WITH c.horario = h.id
			WHERE h.user = $id"
		)->getResult();
	}
}
