<?php

namespace AppBundle\Entity;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealizadaRepository extends \Doctrine\ORM\EntityRepository
{

}